<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Genuinely scheduled, RSVPable events — currently just the 2026
     * pre-nomination campaign itinerary. Past record-of-delivery entries
     * (openings, launches, elections) are `Milestone`s — see MilestoneSeeder.
     */
    public function run(): void
    {
        foreach ($this->campaignItinerary() as $data) {
            Event::firstOrCreate(['slug' => $data['slug']], $data);
        }
    }

    /**
     * Pre-nomination itinerary for the 2026 presidential campaign — courtesy
     * calls region-by-region, then public rallies — ahead of the nomination
     * deadline. Source: campaign itinerary shared 2026-09-18.
     *
     * @return list<array<string, mixed>>
     */
    protected function campaignItinerary(): array
    {
        return [
            [
                'slug' => 'courtesy-calls-nbr-2026',
                'title' => 'Courtesy Calls — North Bank Region',
                'badge' => 'Campaign',
                'date_day' => '16–20',
                'date_month' => 'Sep',
                'date_year' => '2026',
                'js_day' => 16,
                'js_month' => 8,
                'location' => 'North Bank Region',
                'venue' => 'Communities across the North Bank Region',
                'description' => 'Weekend 1 of pre-nomination courtesy calls, touring communities across the North Bank Region.',
                'full_description' => 'The first weekend of courtesy calls ahead of the presidential nominations, touring communities across the North Bank Region.',
                'ics_start' => '20260916T090000Z',
                'ics_end' => '20260920T170000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'courtesy-calls-kiang-foni-2026',
                'title' => 'Courtesy Calls — Kiang & Foni',
                'badge' => 'Campaign',
                'date_day' => '25–27',
                'date_month' => 'Sep',
                'date_year' => '2026',
                'js_day' => 25,
                'js_month' => 8,
                'location' => 'Kiang and Foni',
                'venue' => 'Communities across Kiang and Foni',
                'description' => 'Weekend 2 of pre-nomination courtesy calls, touring communities across Kiang and Foni.',
                'full_description' => 'The second weekend of courtesy calls ahead of the presidential nominations, touring communities across Kiang and Foni.',
                'ics_start' => '20260925T090000Z',
                'ics_end' => '20260927T170000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'courtesy-calls-saloum-wassu-sandu-2026',
                'title' => 'Courtesy Calls — Upper/Lower Saloum, Wassu & Sandu',
                'badge' => 'Campaign',
                'date_day' => '2–4',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 2,
                'js_month' => 9,
                'location' => 'Upper Saloum, Lower Saloum, Wassu and Sandu',
                'venue' => 'Communities across Upper/Lower Saloum, Wassu and Sandu',
                'description' => 'Weekend 3 of pre-nomination courtesy calls, touring Upper/Lower Saloum, Wassu and Sandu.',
                'full_description' => 'The third weekend of courtesy calls ahead of the presidential nominations, touring Upper Saloum, Lower Saloum, Wassu and Sandu.',
                'ics_start' => '20261002T090000Z',
                'ics_end' => '20261004T170000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'courtesy-calls-wcr-2026',
                'title' => 'Courtesy Calls — West Coast Region',
                'badge' => 'Campaign',
                'date_day' => '5–25',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 5,
                'js_month' => 9,
                'location' => 'West Coast Region',
                'venue' => 'Communities across the West Coast Region',
                'description' => 'Weeks 4–6 of pre-nomination courtesy calls, touring communities across the West Coast Region.',
                'full_description' => 'Three weeks of courtesy calls ahead of the presidential nominations, touring communities across the West Coast Region.',
                'ics_start' => '20261005T090000Z',
                'ics_end' => '20261025T170000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'courtesy-calls-kmc-banjul-2026',
                'title' => 'Courtesy Calls — Kanifing Municipality & Banjul',
                'badge' => 'Campaign',
                'date_day' => '1–30',
                'date_month' => 'Nov',
                'date_year' => '2026',
                'js_day' => 1,
                'js_month' => 10,
                'location' => 'Kanifing Municipality and Banjul',
                'venue' => 'Communities across Kanifing Municipality and Banjul',
                'description' => 'Weeks 7–8 of pre-nomination courtesy calls, touring Kanifing Municipality and Banjul.',
                'full_description' => 'The final two weeks of courtesy calls ahead of the presidential nominations, touring Kanifing Municipality and Banjul.',
                'ics_start' => '20261101T090000Z',
                'ics_end' => '20261130T170000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'rally-panchang-saloum-2026',
                'title' => 'Campaign Rally — Panchang, Upper/Lower Saloum',
                'badge' => 'Campaign',
                'date_day' => '2',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 2,
                'js_month' => 9,
                'location' => 'Panchang, Upper/Lower Saloum',
                'venue' => 'Panchang',
                'description' => 'Public campaign rally in Panchang, Upper/Lower Saloum.',
                'full_description' => 'A public campaign rally in Panchang, Upper/Lower Saloum, ahead of the presidential nominations.',
                'ics_start' => '20261002T160000Z',
                'ics_end' => '20261002T190000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'manifesto-launch-banjul-2026',
                'title' => 'Manifesto Launch — Banjul',
                'badge' => 'Campaign',
                'date_day' => '16',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 16,
                'js_month' => 9,
                'location' => 'Banjul',
                'venue' => 'Banjul',
                'description' => 'Launch of the campaign manifesto ahead of the 2026 presidential election.',
                'full_description' => 'The campaign manifesto is launched in Banjul ahead of the 2026 presidential election.',
                'ics_start' => '20261016T160000Z',
                'ics_end' => '20261016T190000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'rally-brufut-sanimentereng-2026',
                'title' => 'Campaign Rally — Sanimentereng, Brufut',
                'badge' => 'Campaign',
                'date_day' => '17',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 17,
                'js_month' => 9,
                'location' => 'Sanimentereng, Brufut',
                'venue' => 'Sanimentereng',
                'description' => 'Public campaign rally in Sanimentereng, Brufut.',
                'full_description' => 'A public campaign rally in Sanimentereng, Brufut, ahead of the presidential nominations.',
                'ics_start' => '20261017T160000Z',
                'ics_end' => '20261017T190000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'rally-brikama-south-manduar-2026',
                'title' => 'Campaign Rally — Manduar, Brikama South',
                'badge' => 'Campaign',
                'date_day' => '17',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 17,
                'js_month' => 9,
                'location' => 'Manduar, Brikama South',
                'venue' => 'Manduar',
                'description' => 'Public campaign rally in Manduar, Brikama South.',
                'full_description' => 'A public campaign rally in Manduar, Brikama South, ahead of the presidential nominations.',
                'ics_start' => '20261017T160000Z',
                'ics_end' => '20261017T190000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'rally-old-yundum-sinchu-2026',
                'title' => 'Campaign Rally — Sinchu, Old Yundum',
                'badge' => 'Campaign',
                'date_day' => '23',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 23,
                'js_month' => 9,
                'location' => 'Sinchu, Old Yundum',
                'venue' => 'Sinchu',
                'description' => 'Public campaign rally in Sinchu, Old Yundum.',
                'full_description' => 'A public campaign rally in Sinchu, Old Yundum, ahead of the presidential nominations.',
                'ics_start' => '20261023T160000Z',
                'ics_end' => '20261023T190000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'rally-kombo-south-gunjur-2026',
                'title' => 'Joint Rally with NUP — Gunjur, Kombo South',
                'badge' => 'Campaign',
                'date_day' => '24',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 24,
                'js_month' => 9,
                'location' => 'Gunjur, Kombo South',
                'venue' => 'Gunjur',
                'description' => 'Joint campaign rally with NUP in Gunjur, Kombo South.',
                'full_description' => 'A joint campaign rally with NUP in Gunjur, Kombo South, ahead of the presidential nominations.',
                'ics_start' => '20261024T160000Z',
                'ics_end' => '20261024T190000Z',
                'is_upcoming' => true,
            ],
            [
                'slug' => 'rally-kombo-east-basorie-2026',
                'title' => 'Campaign Rally — Basorie, Kombo East',
                'badge' => 'Campaign',
                'date_day' => '10',
                'date_month' => 'Oct',
                'date_year' => '2026',
                'js_day' => 10,
                'js_month' => 9,
                'location' => 'Basorie, Kombo East',
                'venue' => 'Basorie',
                'description' => 'Public campaign rally in Basorie, Kombo East.',
                'full_description' => 'A public campaign rally in Basorie, Kombo East, ahead of the presidential nominations.',
                'ics_start' => '20261010T160000Z',
                'ics_end' => '20261010T190000Z',
                'is_upcoming' => true,
            ],
        ];
    }
}
