<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\App;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        App::make(PermissionRegistrar::class)->forgetCachedPermissions();

        $superAdmin = Role::firstOrCreate(['name' => 'super-admin']);
        $admin = Role::firstOrCreate(['name' => 'admin']);

        // `super-admin` is additionally short-circuited by the Gate::before hook
        // in AppServiceProvider, but syncing the permissions keeps Filament
        // Shield's role screen honest. `admin` gets the full set generated by
        // `php artisan shield:generate --all --panel=admin`; tighten per-role
        // in the panel's Roles screen when a narrower role is needed.
        $permissions = Permission::all();

        $superAdmin->syncPermissions($permissions);
        $admin->syncPermissions($permissions);
    }
}
